name: Generate resume from URL and publish it

on:
  repository_dispatch:
    types: [resume_publish]

jobs:
  generate_redirect:
    runs-on: ubuntu-latest

    steps:
      - name: Check API Key
        run: |
          if [ "${{ github.event.client_payload.key }}" != "${{ secrets.REDIRECT_SECRET }}" ]; then
            echo "Invalid key"
            exit 1
          fi

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          - node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Execute
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CHANNEL_ID }}
          REDIRECT_SECRET: ${{ secrets.REDIRECT_SECRET }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: npm run cli -- --url ${{ github.event.client_payload.url }}
